### ISSUE TITLE
Deprecation notice

### ISSUE THREAD

**Issue by rande** [pierrre/gotestcover#10]
Hello,

Not sure I get it right but the deprecation script is wrong as it does not sum up usage. So the final file does not generated a right report.

**Comment by pierrre** [comment]
What do you mean by "it does not sum up usage"?
What is the current output of `gotestcover`?
What is the output of my replacement script?
What do you expect?

**Comment by aeneasr** [comment]
I can confirm that the script not summing up nested packages, for example:
- github.com/foo/bar
  - github.com/foo/bar/baz
    - github.com/foo/bar/baz/zab

In this case, running the script (and gotestcover alike) from `$GOPATH/src/github.com/foo/bar` results in less covered LOCs than running the tests from  `$GOPATH/src/github.com/foo/bar/baz` for package `github.com/foo/bar/baz/zab`. Any ideas?

**Comment by pierrre** [comment]
`gotestcover` and the replacement script should output the same result.

```
echo 'mode: atomic' > coverage.txt && go list ./... | xargs -n1 -I{} sh -c 'go test -covermode=atomic -coverprofile=coverage.tmp {} && tail -n +2 coverage.tmp >> coverage.txt' && rm coverage.tmp
```

It runs `go test` for all packages, then concatenate coverage profiles. That's all.

If you have a problem with gotestcover, I will not fix it because the project is deprecated.

Are you testing a package from another package ?

**Comment by aeneasr** [comment]
> Are you testing a package from another package ?

Yes :)

> gotestcover and the replacement script should output the same result.

They do!

**Comment by pierrre** [comment]
> > Are you testing a package from another package ?
> 
> Yes :)

gotestcover and the replacement script never supported that.
I think it's not a good practice.

**Comment by aeneasr** [comment]
> gotestcover and the replacement script never supported that.

Ok, do you know any tool that supports that?

> I think it's not a good practice.

I think contrary. You should not write unit tests only, and integration tests usually require more than one package. It is also common to have packages like `integration_test` that bootstrap various packages of the application and run tests against it.

**Comment by pierrre** [comment]
The `go test` commands has a `-coverpkg` flag.
But gotestcover doesn't support it (try to add it, you'll understand).

You can adapt the replacement script easily.

**Comment by aeneasr** [comment]
> The go test commands has a -coverpkg flag.

Thank you so much, you helped me tremendously!
