### ISSUE TITLE
Exit status is not correct on failure

### ISSUE THREAD

**Issue by zimmski** [pierrre/gotestcover#3]
The exit status is "0" on failure. So there is no way to tell if a test has failed.
I have a patch for this, but I just did a "hack in an exit status" and not well thought out because I needed it immediately. If you want I can do the PR.

**Comment by zimmski** [comment]
This does not let the program exit with a different exit status. It just prints out that tests failed.

**Comment by pierrre** [comment]
https://github.com/pierrre/gotestcover/blob/master/gotestcover.go#L35

**Comment by zimmski** [comment]
Ahhhh OK, i did not see that, thanks.
